version: '3'
services:
  db_postgres:
    image: postgres:14.1
    volumes:
      - db-data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432
  app_backend:
    image: full-stack-backend
    depends_on:
      - db_postgres
    env_file:
      - .env
    build:
      context: ./
      dockerfile: .dockerfile
    ports:
      - 10000:80

volumes:
  db-data:
